---
title:  "Review of Jordyn Eovito's R Assignment"
author: "Modestos A. Modestou"
date: "2025-03-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Hello Jordyn, 

I saw that you have uploaded an updated repository on GitHub that includes the R Markdown file Script.Rmd. However, the updated repository still doesn't include any other files except the output files, and so I can not run your code on my desktop.

A few comments based on visual inspection of your code since, of course I couldn't run it on my desktop:

1. The code looks good; I didn't find any glaring mistakes.

2. The output files about the chromosomes for maize and teosinte seem to be correct.

3. You mentioned from what you can tell based on the graphs that it seems as though teosinte and maize have the same number of SNPs in each chromosome. My graphs tell the same story. I think, however, it doesn't make sense that the number and distribution of SNPs for maize and teosinte are precisely the same. They shouldn't; maize likely has many more SNPs than its ancestor, teosinte. Unfortunately, I can't offer any suggestions here. I am still struggling myself to figure out how to fix it. 

4. Good job despite the technical difficulties! I wish I could run your code on my desktop to offer more insightful suggestions.